spring.application.name=bookstore-management-system
# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/bookstore_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Abcd@1234

# Hibernate/JPA Settings (Tells Spring to auto-create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080